name: master

on:
   push:
      paths-ignore:
         - 'doc/**'
         - 'documentation/**'
         - '*.md'
         - '*.yml'
         - '.github/workflows/**'
      branches:
         - master

# This will prevent multiple parallel runs, and will a cancel queued runs except the latest one.
concurrency:
   group: 'master-ci'
   # Allow any already started jobs to finish, so we don't leave snapshot builds in a broken state.
   cancel-in-progress: false

permissions:
   contents: read

jobs:
   validate-api:
      name: Validate API
      if: github.repository == 'kotest/kotest'
      uses: ./.github/workflows/run-gradle.yml
      secrets: inherit
      with:
         runs-on: ubuntu-latest
         ref: ${{ inputs.ref }}
         task: apiCheck

   build-and-publish-snapshots:
      strategy:
         matrix:
            include:
               # KMP
               -  os: ubuntu-latest
                  args: -P"kotest_enabledPublicationNamePrefixes=KotlinMultiplatform"
               # JVM
               -  os: ubuntu-latest
                  args: -P"kotest_enabledPublicationNamePrefixes=jvm"
               # JS
               -  os: ubuntu-latest
                  args: -P"kotest_enabledPublicationNamePrefixes=js"
               # Linux
               -  os: ubuntu-latest
                  args: -P"kotest_enabledPublicationNamePrefixes=linux"
               # Wasm
               -  os: ubuntu-latest
                  args: -P"kotest_enabledPublicationNamePrefixes=wasmJs"
               # Publish 'common' components (KotlinMultiplatform,jvm,js) only on Linux, to avoid duplicate publications
               -  os: ubuntu-latest
                  args: -P"kotest_enabledPublicationNamePrefixes=android"
               # Kotest BOM
               -  os: ubuntu-latest
                  args: -P"kotest_enabledPublicationNamePrefixes=KotestBom"

               # Windows: MinGW
               -  os: windows-latest
                  args: -P"kotest_enabledPublicationNamePrefixes=mingw"

               # Apple: macOS
               -  os: macos-latest
                  args: -P"kotest_enabledPublicationNamePrefixes=macOS"
               # Apple: iOS
               -  os: macos-latest
                  args: -P"kotest_enabledPublicationNamePrefixes=iOS"
               # Apple: tvOS
               -  os: macos-latest
                  args: -P"kotest_enabledPublicationNamePrefixes=tvOS"
               # Apple: watchOS
               -  os: macos-latest
                  args: -P"kotest_enabledPublicationNamePrefixes=watchOS"


      uses: ./.github/workflows/run-gradle.yml
      secrets: inherit
      with:
         ref: ${{ inputs.ref }}
         task: >
            -P"kotest_enableKotlinJs=true"
            -P"kotest_enableKotlinNative=true"
            ${{ matrix.args }}
            --no-configuration-cache
            check publishToAppropriateCentralRepository
         runs-on: ${{ matrix.os }}
